- docker/CMSRucioClient/scripts/syncSite.py
The `syncSite.py` script provides a mechanism to synchronize the datasets (and their replicas) for a given site between PhEDEx and Rucio.  It's meant to handle the case where one site's namespace is visible to both systems, but we just need to keep the registered contents the same.
> Add script to synchronize site contents.

- docker/CMSRucioClient/scripts/CMSRucio.py
- docker/CMSRucioClient/scripts/cmstfc_lfn2pfn.py
- docker/CMSRucioClient/scripts/syncSite.py
Disregarding good practices, this commits contains several (unrelated) things
- adding the `cmstfc_lfn2pfn.py` plugin (if merged, in the doc for the evaluation committee we can point to the dmwm githhub repo rather than mine)
- some improvements in the `CMSRucio.py` module
- using rucio.client.client.Client rather than different clients for DID, Replicas, ...
- added `get_file_url`, `get_global_url` and `check_storage` method which where previously in `syncSite.py`
- added some checks and retries for das and data service
- some bug fixes and pylint suggested changes
- some improvements in the `syncSite.py` tool
- added class NodeSync for injecting into the RSE protocol extended attributes the relevant TFC rules
- added `get_transferred_datasets` that gets the list of datasets subscribed …
> Committing recent evolutions in the sync code and adding TFC plugin

- docker/CMSRucioClient/scripts/cmsdatareplica.py
- docker/CMSRucioClient/scripts/synccmssites.py
Workaround for the list_replicas bug (just catching the exception and returning an empty list). Also pushing a change in synccmssites done some time ago to force the script running some deletions even when sites are heavily out of sync.
> workaround for a bug in list_replicas

- docker/CMSRucioClient/scripts/cmsrses.py
- docker/CMSRucioClient/scripts/k8s_sync_sites.sh
Set to `--dry` run in cronjob script.  Let's put it in, see if the dry run looks ok, then fix.
Can remove `_Buffer` manually.  Need to check also if this will work with the dataset sync script, when we start to sync Tape over. @sartiran do you know off-hand if the RSE `pnn` attribute is used to link the RSE to the PhEDEx node for sync?
> Sync T1 tape sites as RSE '_Tape'

- docker/CMSRucioClient/scripts/cmsrses.py
Adding one `/` to fix https://its.cern.ch/jira/browse/CMSRUCIO-221
Tested on a T2_US_Florida_Temp and T2_US_Purdue on int server, and they look on now.
Still not optimal, we might need to understand why this is happening at Rucio level
> Correct prefix for few broken RSE

- docker/CMSRucioClient/scripts/k8s_sync_users_links.sh
- docker/CMSRucioClient/scripts/syncEgroupsToGroupAccounts.py
Split the cronjobs into two pieces putting the most urgent in one hour. Also requires a CMSKubernetes change to helm
> Split cron jobs into two Fix #217

- docker/CMSRucioClient/scripts/cmslinks.py
Can be removed once `T2_US_Caltech_Ceph` is decomissioned
> No link between Caltech_Ceph and Caltech

- UserDMTools/README.md
- UserDMTools/lib/did_upload.py
- UserDMTools/lib/templates/dataset-upload.yml
- UserDMTools/lib/templates/file-upload.yml
- UserDMTools/requirements.txt
- UserDMTools/upload.py
Fix #275  (User dedicate CLI interface for RUCIO data injection)
- Adds a CLI interface for local data upload in rucio
- Files can be uploaded in isolation or as a part of a dataset as per instruction in README
- Created directory for user data management scripts
> Adding user-dm-scripts for file and dataset uploads

- UserDMTools/lib/did_upload.py
The function in concern (`get_pfns_temp`) is available inside the same file.
> Removing wrong import, was a residual of refactoring

- docker/CMSRucioClient/scripts/account_to_scope_mapping.py
- docker/CMSRucioClient/scripts/k8s_sync_users_links.sh
Fix #388 
We query Rucio to get the list of group accounts. 
(We choose this approach instead of queries CRIC API, to avoid inconsistencies between accounts and scopes).
The three types of group accounts that exist today are: 
1. Local Users
2. Legacy Physics Group Accounts (top, higgs, heavy_ions)
3. New Physics Group Accounts (pog_tau_group) [ Note: new group have a `_group` suffix ]
The script has options to include/exclude considering these group accounts for scope creation.
Namely: 
1. `-include_local_users_accounts`
2. `-only_include_accounts_with_group_suffix`
> Adding script to make group scopes from list of group accounts in Rucio

- docker/CMSRucioClient/scripts/setSiteAvailability
We are in the process of migrating `T2_FR_GRIF_LLR` and `T2_FR_GRIF_IRFU` to a single site `T2_FR_GRIF`. 
Meanwhile, we want to disable data writes to the site. https://its.cern.ch/jira/browse/CMSTRANSF-452.
Hence preventing auto-updates to availability status.
> Update setSiteAvailability - Skip LLR and IRFU

- docker/CMSRucioClient/Dockerfile.loadtest
- docker/CMSRucioClient/loadtest/loadtest.py
Load tests files should be reinstantiated even in the absence of write availability to avoid deadlocks with cmmsst.
Adding ReplicationRuleCreationTemporaryFailed exception during upload. Need to review the use of this again.
> Adding ignore_availability flag to loadtest uploads

- docker/CMSRucioClient/scripts/syncUserRoles.py
Data already fetched here,
https://github.com/dmwm/CMSRucio/blob/d85604436bc3d80efbb49b2d4489e5297c6bb78d/docker/CMSRucioClient/scripts/syncUserRoles.py#L126-L129
> removing redundant call to cric API

- docker/CMSRucioClient/scripts/capacity_lucene.json
- docker/CMSRucioClient/scripts/k8s_sync_sites.sh
- docker/CMSRucioClient/scripts/setSiteCapacity
Updates static site usage from site capacity Fix #463 
This script will sync rucio `static` usage from the site capacity dashboard. 
https://cmssst.web.cern.ch/cgi-bin/set/SiteCapacity
`T2_CH_CERN` and `T0_CH_CERN` are excluded from this sync and will be manually updated by T0_operations.
> Add siteCapacity Script to Cron Jobs

- docker/CMSRucioClient/scripts/k8s_sync_users_links.sh
- docker/CMSRucioClient/scripts/syncCustomRoles.py
- src/policy/permission.py
The script syncs custom roles for capacity managers at CERN [CMS_TIER_0_OPS group in CRIC](https://cms-cric.cern.ch/api/accounts/group/query/?json&name=CMS_TIER_0_OPS).
I have created a general outline. The function can be used as a  skeleton for such site-specific roles. If things tend to be applied more generally, we shall try to add roles for individual users who belong to a particular e-group.
Further, we use the members of this list to provide permissions to set_rse_usage - to set static, and set_rse_limits - to set MinFreeSpace. 
Fix #468
> Adding custom role - site_capacity_manager - for T0 and T2 CERN Disks

- .github/workflows/loadtest-docker-image.yml
set-output will be deprecated by github in a month. Using the recommend "GITHUB_ENV" file. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Additional patch for #496
> Using github_env file to pass tag name

- docker/CMSRucioClient/scripts/account_to_scope_mapping.py
- docker/CMSRucioClient/scripts/k8s_sync_users_links.sh
The DB schema places a char limit of 20 for scope length, this we need to trim, `_local_users` and `_group` from local users and physics group accounts.
Fix #531
> Enable scope creation for local users accounts

- build-rucio-images.sh
- src/policy/CMSRucioPolicy/algorithms/auto_approve.py
- src/policy/CMSRucioPolicy/schema.py
Hi Eric
I thought I had created this PR already. 
This is a tiny update in the auto_approval flow.
- We switched to using the new_activity `User AutoApprove` for auto-approval rules from Data-Brokering
- Added a new limit of 50 TB for rules that target a specific RSE
> Cmsrucio autoapprove policy updates

- SiteOps/MyRSEs.py
- docker/CMSRucioClient/scripts/syncUserRoles.py
- src/policy/CMSRucioPolicy/permission.py
Fix #526 
Extras
- Some cleanup of old commented code
- Change quota approvers to more generic site admins
Documentation for Site Admins: https://cmsdmops.docs.cern.ch/SiteAdmins/Corrupted%20Files/
> Provide site admins permissions to declare replica as bad

- docker/CMSRucioClient/scripts/updateDDMQuota
CRAB was using these values to select RSEs.
https://github.com/dmwm/CRABServer/issues/7714
> Set ddm quota as integers

- docker/CMSRucioClient/scripts/updateDDMQuota
This builds on top of #547
The intention is to ensure an almost equal distribution of locked space:
- without needing to rebalance later
- prevent "busy" sites, where recent data is removed, while much older and not accessed data lives at other sites
@belforte do you have any suggestions to better achieve the specified goals?
> Refine ddm_quota to include dynamic space

- docker/CMSRucioClient/scripts/setSiteAvailability
Storage migration for T2_FI_HIP
https://its.cern.ch/jira/browse/CMSDM-68
Long term solution to make skip updates using RSE attributes: https://github.com/dmwm/CMSRucio/issues/561
> exclude T2_FI_HIP from availability updates

- docker/CMSRucioClient/scripts/capacity_lucene.json
- docker/CMSRucioClient/scripts/setSiteCapacity
Fix #573 
Dry Run output: 
```
INFO Updating static usage, from 0.00TB to 228000.00TB, for T0_CH_CERN_Tape, dry_run=True
INFO Updating static usage, from 0.00TB to 126400.00TB, for T1_US_FNAL_Tape, dry_run=True
INFO Updating static usage, from 0.00TB to 24424.00TB, for T1_UK_RAL_Tape, dry_run=True
INFO Updating static usage, from 0.00TB to 41080.00TB, for T1_IT_CNAF_Tape, dry_run=True
INFO Updating static usage, from 0.00TB to 12640.00TB, for T1_ES_PIC_Tape, dry_run=True
INFO Updating static usage, from 0.00TB to 37900.00TB, for T1_DE_KIT_Tape, dry_run=True
INFO Updating static usage, from 0.00TB to 25000.00TB, for T1_RU_JINR_Tape, dry_run=True
INFO Updating static usage, from 0.00TB to 32548.00TB, for T1_FR_CCIN2P3_Tape, dry_run=True
```
> update static usage for tape rses

- .github/workflows/rucio-release-images.yml
Adding workflows that make the following assumptions:
1. The `git tag` will have the format `release-RUCIO_VERSION.cmsX`.
2. It extracts the rucio version and passes it to the build script to use the appropriate rucio image.
The workflow builds the following images:
- rucio-probes
- rucio-server
- rucio-daemons
- rucio-ui
Fix #516
> github actions workflow for rucio release images

- src/policy/CMSRucioPolicy/permission.py
Fix #623
This commit checks if the `issuer` (account performing the `approve` operation) is a `rule_approver` for all rses that the expression can evaluate.
> Fix approve permissions for multi-rse expression

- docker/CMSRucioClient/scripts/updateDDMQuota
This PR
1. Makes ddm_quota quadratic to dynamic + free fraction instead of linear. This is because we want RSEs with low dynamic + free fraction chosen with less probability compared to the current implementation
2. Normalizes the weights between 0 and 100
3. Makes the script a bit more modular
One thing to note
- I do linear (Max-Min) normalization. This means that the RSE with the lowest dynamic + free fraction will have 0 ddm_quota
And one question: Can someone explain or point me the relevant code exactly how Rucio uses this weight?
Cheers
> Make ddm_quota calculation quadratic and normalized

- src/policy/CMSRucioPolicy/algorithms/auto_approve.py
- src/policy/CMSRucioPolicy/permission.py
Fix #637
Moves all checks from the `auto_approve` function to `_check_for_auto_approve_eligibility` under `perm_add_rule`.
> Auto approve refactoring

- docker/CMSRucioClient/scripts/CMSRSE.py
Fix: https://github.com/dmwm/CMSRucio/pull/639
Update loadtest from SITECONF storage.json on  rse `cms_type: real` only
> Fix: Disable loadtest on test/temp rses

- docker/CMSRucioClient/scripts/cmslinks.py
Change default PNN value. Modified from None to the `site` attribute from the `SITECONF` file.
Improves link selection by making choose a closer one than in a None value case
FIX: https://github.com/dmwm/CMSRucio/issues/385
> Get default PNN from SITECONF file

- src/policy/CMSRucioPolicy/permission.py
Fixes https://github.com/dmwm/CMSRucio/issues/733
> Restrict rse expression to single rse when ask_approval is used

- docker/CMSRucioClient/Dockerfile
- docker/CMSRucioClient/Dockerfile.centos7
- docker/CMSRucioClient/build.sh
For #652
Migration of CMSRucioClient base image to Alma9. Build script for CMSRucioClient image.
> Migrate CMSRucioClient base image to almalinux9

- docker/rucio-probes/Dockerfile
We'll upgrade int to 33.6.1 and these patches are already available in that release
> Remove 2 probe patches for PR 122 and 123

- src/policy/CMSRucioPolicy/permission.py
For now, I am only allowing an admin account for a quick fix to allow wmcore_pileup to carry on its testing but these needs to be thought out and defined clearly.
> Allow non USER datatier in non cms scopes for admin accounts

- docker/rucio_client/Dockerfile.loadtest
Fixes #653 
Loadtest image is based on the client image that Dennis upgraded to ALMA9 recently. I've built the most recent version of the new rucio_client image [1,2] and built the loadtest image based on that [3]. The only change I've done was to remove the ENTRYPOINT which is redundant as the process is initiated by the following command defined in the relevant helm chart [4,5]. You can find my tests here [6]
[1] https://github.com/dmwm/CMSRucio/blob/3889a60c6da5ef0f60c4ec184d6a35643aecacfd/docker/rucio_client/Dockerfile 
[2] https://registry.cern.ch/harbor/projects/3667/repositories/rucio_client_hasan/artifacts-tab
[3] https://registry.cern.ch/harbor/projects/3667/repositories/cmsloadtest_hasan/artifacts-tab 
[4] https://github.com/dmwm/CMSRucio/blob/5945331ec29fc2c1629f647fe6174f981970 …
> Upgrade loadtest image to ALMA9

- docker/rucio_client/loadtest/loadtest.py
Loadtests crash when there are problems with deletion at the destination site. 
```
2024-05-10 11:31:59,338 __main__:INFO:New link between T2_EE_Estonia and T2_RU_INR, creating a load test rule this cycle
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/lib64/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "./loadtest.py", line 356, in run
tape_rses_require_approval
File "./loadtest.py", line 229, in update_loadtest
client.add_replication_rule(**rule)
File "/usr/local/lib/python3.6/site-packages/rucio/client/ruleclient.py", line 91, in add_replication_rule
raise exc_cls(exc_msg)
rucio.common.exception.ReplicationRuleCreationTemporaryFailed: …
```
> catch temporary rule creation failed exception

- docker/rucio_client/scripts/CMSRSE.py
Fixes #796 
Dry-run is as expected:
```
Checking T2_BR_UERJ and type prod-real
20240510 14:28:44  INFO - setting attribute loadtest to value True for rse T2_BR_UERJ. Dry run, skipping
```
@dynamic-entropy we'd better double check and not merge this on friday. The following lines are concerning 
```
Checking T1_ES_PIC_Disk and type prod-real
20240510 14:27:49  INFO - Deleting davs from T1_ES_PIC_Disk (Dry run, skipping)
20240510 14:27:49  INFO - Deleting srm from T1_ES_PIC_Disk (Dry run, skipping)
20240510 14:27:49  INFO - Deleting root from T1_ES_PIC_Disk (Dry run, skipping)
```
although I see the same lines in the prod logs
> Make loadtests be synced from gitlab

- src/policy/CMSRucioPolicy/algorithms/auto_approve.py
- src/policy/CMSRucioPolicy/permission.py
- src/policy/CMSRucioPolicy/schema.py
This activity can only be used by the `crab_tape_recall` account.
For https://github.com/dmwm/CRABServer/issues/8354
> Add Analysis Tape Recall activity 

- .github/workflows/rucio-release-images.yml
- docker/rucio_client/Dockerfile
- docker/rucio_client/scripts/CMSRSE.py
- docker/rucio_client/scripts/k8s_sync_sites.sh
This PR updates cron job scripts to sync RSE protocol from GitLab on the integration server.
Additionaly, to enable testing it, modifies the docker commands to checkout the CMSRucio repo at appropriate tag for the rucio client.
Fixes https://github.com/dmwm/CMSRucio/issues/765
> Sync int rses

- docker/rucio_client/Dockerfile
The latest release of Gfal2-util (v1.9.0) removed the `Provides: gfal2-util`
Gfal2 package now only provides: `python3-gfal2` and `python3-gfal2-util`
Additionally, removing `gfal2-plugin-xrootd`, since its already bundled with `gfal2-all`.
> Fix deprecated package name gfal2-util

- docker/rucio-daemons/Dockerfile
- docker/rucio-server/Dockerfile
- docker/rucio-ui/Dockerfile
@Panos512 reported a failed `get_rse_info` after upgrading to rucio 35. 
```
✘ ppaparri@lxplus942  ~  rucio-admin rse info T0_CH_CERN_Tape
An unknown exception occurred.
Details: no error information passed (http status code: 500)
Rucio exited with an unexpected/unknown error, please provide the traceback below to the developers.
Traceback (most recent call last):
File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel9/py3/current/bin/rucio-admin", line 97, in new_funct
return function(*args, **kwargs)
File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel9/py3/current/bin/rucio-admin", line 533, in info_rse
rse_limits = client.get_rse_limits(args.rse)
File "/cvmfs/cms.cern.ch/rucio/x86_64/rhel9/py3/current/lib/python3.9/site-packages/rucio/client/rseclient.py", line 569, in get_rse_limits
raise …
```
> patch for json serialisation for empty dirs

- docker/rucio_client/scripts/availability_lucene.json
- docker/rucio_client/scripts/setSiteAvailability
Fixes #828 
Based on Rucio status in [1]
I realized that we're not updating `availability_read`. @dynamic-entropy how about disabling `availability_read` if rucio status is one of `downtime_stop`, `parked`, `disabled`?
@stlammel fyi
[1] https://twiki.cern.ch/twiki/bin/view/CMS/SiteSupportSiteStatusSiteReadiness
> Update siteAvailability script according to the new rucio status

- docker/rucio-daemons/Dockerfile
In the scope of https://github.com/dmwm/CMSRucio/issues/806 patching https://github.com/rucio/rucio/pull/7106 which is a fix to https://github.com/rucio/rucio/issues/7105
This is needed to be able to run replica recoverer properly finally and give feedback in the rucio workshop ideally.
> Patch rucio 7106 which is a fix of rucio 7105

- docker/rucio-daemons/Dockerfile
- docker/rucio-server/Dockerfile
Modified the patch to make Reaper use a subpath (/store) instead of root (/) for token scopes.
Two reasons:
- Some sites do not allow a token scoped at `/`. 
- I preferred this over patching the reaper to never use tokens for the time being
Did some additional cleanup of merged patches.
> Add patch for CMS token path calculations

- helm/rucio-consistency/Chart.yaml
- helm/rucio-consistency/templates/deployment.yaml
- helm/rucio-consistency/values.yaml
This PR is a duplicate of https://github.com/dmwm/CMSRucio/pull/844, providing additional changes and merging into master as requested.
The PR includes a new version of rucio-consistency helm chart. The new chart adds some environment variables that will be used for prometheus.
> update rucio-consistency helm chart for adding prometheus monitoring

- src/policy/CMSRucioPolicy/permission.py
MIT Tape has developed a rest interface that would allow it to be treated as a regular tape.  https://its.cern.ch/jira/browse/CMSDM-234
> Remove archive_timeout restriction from MIT Tape

- docker/rucio-probes/Dockerfile
Related to https://github.com/dmwm/CMSRucio/issues/747
Applies https://github.com/rucio/probes/pull/151 which allows rules count and volume monitoring per rse, activity and state.
When the PR is available in our rucio version, the changes can be removed.
> add patch for rucio/probes#151

- docker/rucio_client/scripts/updateDDMQuota
Fixes #877 
Sets the dm_weight to 0 if a site's usage is above its quota or its `availability_write` is False.
I ran it manually and the result is as expected:
```
[haozturk@lxplus960 scripts]$ python3 updateDDMQuota 
Set dm_weight for T2_UK_SGrid_RALPP to 13
Set dm_weight for T2_IT_Bari to 13
Set dm_weight for T2_UK_London_IC to 30
Set dm_weight for T1_UK_RAL_Disk to 67
Set dm_weight for T2_IT_Rome to 0
Set dm_weight for T2_TR_METU to 0
Set dm_weight for T1_IT_CNAF_Disk to 57
Set dm_weight for T2_BR_UERJ to 0.0
Set dm_weight for T2_DE_RWTH to 8
Set dm_weight for T2_FI_HIP to 2
Set dm_weight for T2_RU_ITEP to 35
Set dm_weight for T2_TW_NCHC to 0
Set dm_weight for T2_KR_KISTI to 7
Set dm_weight for T2_IN_TIFR to 0
Set dm_weight for T2_UK_SGrid_Bristol to 0
Set dm_weight for T2_ES_IFCA to …
```
> Set dm_weight to 0 if a site's usage is above its quota or its availability_write is False

- docker/rucio_client/scripts/setSiteAvailability
When RSE's availability is updated, the flag availability_read should be set automatically, similar to current availability_write and availability_delete
Relevant issue: https://github.com/dmwm/CMSRucio/issues/883
> availability_read set available automatically

- docker/rucio-probes/Dockerfile
Related to https://github.com/dmwm/CMSRucio/issues/747
Patch https://github.com/rucio/probes/pull/154. Can be removed when PR is merged and new probes version is available.
> PATCH: probes#154 | check probes and rules

- src/policy/CMSRucioPolicy/__init__.py
- src/policy/CMSRucioPolicy/algorithms/tape_collocation.py
- Reworking the way initialization is done. (Should avoid recursive import errors, but I can't say for sure. Worth testing out in int for *sure*)
- Makes most functions static or class methods to compile with the requirements of the policy package `register` method. (Putting in a similar documentation issue shortly on rucio/docs, none of this explained.)
- Forces everything to use the CMS scope and throws a DID error otherwise instead of verifying after doing a bunch of operations.
> Metadata Plugin Initialization Correction

- src/policy/CMSRucioPolicy/__init__.py
- src/policy/CMSRucioPolicy/algorithms/tape_collocation.py
Initialization of the plugin was failing due to circular imports - solved by moving imports inside `get_algorithms()`. 
Circular import was because when importing the original policy, the config is needed for `FTS3TapeMetadataPlugin` subclasses,  but the schema in the policy package is required to pick up the config. 
This isn't caught in dev instances because they all use a default schema.
> Changing import order to avoid circular imports in policy packages

- docker/rucio_client/scripts/setSiteAvailability
Based on [1], we don't want to switch off availability write for tapes based on occupancy. Rather, if a tape site has more than 98%, the production output rule creation is managed by `wmcore_output_tape` attribute [2] and we will inform T0 to stop rule creation to that specific site (in the near future, we would like this to be done automatically as well). This will help us manage stuck/suspended rules which are trying to transfer files to the site since we will tackle the actual issue instead of the RSE excluded from writing such as [3].
[1] https://github.com/dmwm/rucio-flux/pull/399
[2] https://github.com/dmwm/CMSRucio/blob/master/docker/rucio_client/scripts/setWmcoreTapeOutput
[3] https://its.cern.ch/jira/browse/CMSDM-319
> Excluded Tape RSEs from switch off site availability based on  occupancy

- src/policy/CMSRucioPolicy/permission.py
Updated `perm_add_bad_pfns` function to check if a user is CMS site admin similar to `perm_declare_bad_file_replicas` which was causing #938
> Fix #938: Included CMS site admin check for perm_add_bad_pfns similar to perm_declare_bad_file_replicas

- src/policy/CMSRucioPolicy/algorithms/tape_colocation.py
Ref this jira ticket: https://its.cern.ch/jira/browse/CMSDM-315
Additions:
Schema #1
File Metadata:
As given by Rucio hints:
* Size
* MD5
* Adler32
Additional Hints:
* Activity (default to "default" if not given)
* Level 3 length and size (if parent container exists)
- Length - total number of files in the parent container, including nested datasets/containers
- Size - total size of all files in the parent container, including nested datasets/containers
> CMSDM-315: Include additional metadata in the tape colocation plugin

- docker/rucio_client/scripts/cmslinks.py
Fixes #837 
Set distances between:
A (West Europe) and C (East Europe) regions to 11
C (East Europe) and D (Asia) regions to 12
> Fix #837: Distances for Europe and Asia

- src/policy/CMSRucioPolicy/algorithms/tape_colocation.py
Revert the tape metadata changes so we can build a 38.2
This reverts commit e4da9eccf50b180356186ae557d37b29b742af0a. 
This reverts commit 32f6a98129fb4cc1c8a1f513528ba12d0d572a85.
> Revert "CMSDM-315: Include additional metadata in the tape colocation plugin"
