dmwm/CMSRucio

docker/CMSRucioClient/scripts/insertDataset.py

CMS blocks are inserted as Rucio datasets. CMS Datasets are inserted as containers and as datasets.

Script to insert a CMS dataset

---

docker/CMSRucioClient/scripts/CMSRucio.py

with the same return format as PhEDEx

Add the first bit of data discovery needed 

---

docker/CMSRucioClient/scripts/insertDataset_v2.py
docker/CMSRucioClient/scripts/registerFile.py

Hi,
a couple of adds to the script directory.
1- insertDataset_v2.py: rewrite/evolution (or just my own interpretation) of insertDataset.py. 
2- registerFile: just a script that register a file which is already on storage

Insert dataset

---

docker/CMSRucioClient/scripts/syncSite.py

Also fixes the `check_storage` method.

Allow syncSite to be run on a list of particular datasets.

---

docker/CMSRucioClient/Dockerfile

I don't know why PyPi doesn't pick this up from the cms_rucio requirements, but....
Eric

Add flask for python to docker container.

---

docker/CMSRucioClient/scripts/CMSRucio.py
docker/CMSRucioClient/scripts/syncSite.py

Hey @sartiran I'd appreciate it if you gave this a try. You can see my refactor restores some things to function parameters instead of instance variables and moves ~all the common code out into CMSRucio.

Refactor sync script

---

docker/CMSRucioClient/scripts/CMSRucio.py
docker/CMSRucioClient/scripts/syncSite.py

and use replica client instaed of rse manager

Add userpass option to syncSite

---

docker/CMSRucioClient/Dockerfile
docker/rucio_dev_env/Dockerfile
docker/rucio_dev_env/README.md

and some dev stuff to the client container

Add a development environment container

---

docker/CMSRucioClient/scripts/cmslinks.py
docker/CMSRucioClient/scripts/cmsrses.py
docker/CMSRucioClient/scripts/cmstfc.py
docker/CMSRucioClient/scripts/phedex.py

Refactored things so that the scripts synchronizing data and updating RSEs can use the same base module (for the PhEDEx related methods, which are shared). I've renamed things for I've not yet implemented all functionalities of e.g. updateRSE in cmsrses.py
- phedex.py: a class with phedex related methods (retreiving info from datasvc and das). It has a command line interface just for testing the different functions 
- cmsrse.py: class for a CMSRSE with a method update() that creates or updates the RSE according to the corresponding PNN (plus instructions passed to command line)
Still some to be done: better logging, a better cli for phedex.py, manage RSE distances
Also the data synchronization part is in the pipe.

Modules for phedex related methods and for RSE updates

---

DMOps/get_account_info.py
DMOps/get_stuck_rules.py
DMOps/list_replicas.py
DMOps/list_subscription_rules.py
DMOps/list_subscriptions.py
DMOps/update_account.py
DMOps/update_rule.py

helps ops to find info about subscriptions/ stuck rules and accounts.
using rucio-client.

scripts for ops

---

docker/CMSRucioClient/scripts/cmsdatareplica.py
docker/CMSRucioClient/scripts/phedex.py

@nsmith- notice any issues? There will be a PR against CMSKubernetes too

Fetch custodial and group

---

src/cric_user.py
src/user_to_site_mapping.py

and refactor and move adding identies

Make DNs a list

---

DMOps/get_stuck_rules.py

updated function name
@ericvaandering

updated get_stuck_rules script

---

tests/host_run.sh
tests/run_tests.sh

Maybe we can expand the testing a bit more in the future.

Make test result a bit more clear

---

.gitignore
docker/CMSRucioClient/Dockerfile
docker/CMSRucioClient/scripts/CMSRSE.py
docker/CMSRucioClient/scripts/EXAMPLE_STORAGE.json
docker/CMSRucioClient/scripts/updateRSEs_new.py

Get python3 in the container
Add example file for KIT

Add new script and class for syncing RSEs

---

docker/CMSRucioClient/scripts/availability_lucene.json
docker/CMSRucioClient/scripts/k8s_sync_sites.sh
docker/CMSRucioClient/scripts/setSiteAvailability

Add a script and query to set site availability.

---

docker/CMSRucioClient/traces/collect_send_traces.py

update WMArchive code because the ES db changed.

update WMArchive code because the ES db changed.

---

DMOps/get_error_logs.py
DMOps/list_dids.py

added script for parsing rucio logs
@ericvaandering

added script for parsing error logs

---

DMOps/modify_protocol.py
DMOps/nanoaod_subscription.py

Also provides a history of the subscriptions

Small updates to ops scripts

---

DMOps/fix_tape_file_exists.py

Fixes destination file exists issue: files are OK if
- The PFN has correct size
- The PFN has correct checksum
- The PFN has 'NEARLINE' in the user.status xattr (i.e., archived)
This is a short-term hack. Long-term solution:
https://github.com/rucio/rucio/issues/4447

A tool to mark tape files as OK if the site has them

---

docker/CMSRucioClient/scripts/setRucioFromGitlab

Fix rse sync script for missing 'fts' key

---

docker/rucio-probes/Dockerfile

Fix minor change in prometheus_client format.
PR 97

check_transfer_queues_status_BUG

---

helm/rucio-cvmfs/.helmignore
helm/rucio-cvmfs/Chart.yaml
helm/rucio-cvmfs/templates/NOTES.txt
helm/rucio-cvmfs/templates/_helpers.tpl
helm/rucio-cvmfs/templates/sc-pvc.yaml
helm/rucio-cvmfs/values.yaml

Add a helm chart which will mount the CVMFS grid.cern.ch area

Cvmfs chart

---

DMOps/dynamic_ddmquota_update.py

[ggus-ticket-158850](https://ggus.eu/index.php?mode=ticket_info&ticket_id=158850)

Correct site name for T2 Estonia

---

DMOps/dynamic_ddmquota_update.py

Setting the ddm_quota to zero until the site is fully commissioned
https://ggus.eu/index.php?mode=ticket_info&ticket_id=157739

Update dynamic_ddmquota_update.py for new T2_FR_GRIF

---

docker/rucio-server/Dockerfile
docker/rucio-server/build-rucio-images.sh

Igor's patch no longer needed

---

src/policy/schema.py

- User and Group Scopes managed by rucio can only write to `/store/user/rucio/username` and `stote/group/rucio/groupname` namespace.

adding lfn and scope validation for groups

---

docker/rucio-consistency/build_image.sh
helm/rucio-consistency/Chart.yaml
helm/rucio-consistency/templates/consistency-configmap.yaml

Fix CE config

---

docker/CMSRucioClient/scripts/CMSRSE.py

Example dry-run output for `T2_IT_Bari` with `global-ro` access type. 
```
Checking T2_IT_Bari and type prod-real
20230411 14:23:12  INFO - Deleting definition which is not as expected (Dry run, skipping)
20230411 14:23:12  INFO - {
"domains": {
"lan": {
"delete": 0,
"read": 0,
"write": 0
},
"wan": {
"delete": 3,
"read": 3,
"third_party_copy_read": 3,
"third_party_copy_write": 3,
"write": 3
}
},
"extended_attributes": null,
"hostname": "xrootd.ba.infn.it",
"impl": "rucio.rse.protocols.gfal.Default",
"port": 1094,
"prefix": "/",
"scheme": "root"
}
20230411 14:23:12  INFO - expected (Dry run, skipping)
20230411 14:23:12  INFO - {
"scheme": "root",
"hostname": "xrootd.ba.infn.it",
"port": 1094,
"extended_attributes": null,
"domains": {
"wan": {
"read": 3,
"write": 0, …
```

adding support for global-ro access level in gitlab siteconf

---

UserDMTools/user_data_registration/.gitignore
UserDMTools/user_data_registration/Readme.md
UserDMTools/user_data_registration/main.py
UserDMTools/user_data_registration/src/config/files.json
UserDMTools/user_data_registration/src/config/options.json
UserDMTools/user_data_registration/src/gfal_transfers/count_files.py
UserDMTools/user_data_registration/src/gfal_transfers/gfal_overwrite_test.py
UserDMTools/user_data_registration/src/gfal_transfers/s1_gfal_transfer.py
UserDMTools/user_data_registration/src/utils/colors.py
UserDMTools/user_data_registration/src/utils/create_rule.py
UserDMTools/user_data_registration/src/utils/fts_transfer.py
UserDMTools/user_data_registration/src/utils/lfn2pfn.py
UserDMTools/user_data_registration/src/utils/prepare_transfer.py
UserDMTools/user_data_registration/src/utils/register_blocks_and_containers.py
UserDMTools/user_data_registration/src/utils/register_files.py

Adding initial scripts to use for user data registration. 
These need more refinement as more and more users start using them.
Fix #441

Adding user data registration scripts

---

docker/CMSRucioClient/scripts/setSiteAvailability

Skip T2_GR_Ioannina to enable the availability_delete for [CMSTRANSF-403](https://its.cern.ch/jira/browse/CMSTRANSF-403)

T2_GR_Ioannina decommission fix

---

.github/workflows/loadtest-docker-image.yml

Create loadtest-docker-image.yml 

---

docker/CMSRucioClient/loadtest/loadtest.py

**Summary**
Fixes #500 
Update list_dids argument to match Rucio

Fix:  loadtest list_dids

---

.github/workflows/loadtest-docker-image.yml

https://github.com/dmwm/CMSRucio/issues/496
(Tested in fork)

fix missing registry and security warning

---

docker/rucio-consistency/build_image.sh

Version bump for the Docker image version

Use rucio consistency pip

---

build-rucio-images.sh
docker/rucio-daemons/Dockerfile
docker/rucio-server/Dockerfile
docker/rucio-ui/Dockerfile
src/policy/CMSRucioPolicy/__init__.py
src/policy/CMSRucioPolicy/algorithms/auto_approve.py
src/policy/CMSRucioPolicy/algorithms/lfn2pfn.py

Final touches for CMSRucioPolicy Package
This commit is mapped to the rucio-1.31.3.cms3 docker images.
- This introduces the auto_approve plugin algorithm in the policy package

Rucio Auto Approval

---

DMOps/fix_tape_file_exists.py

Fix mismatch between Rucio '0cf84f0a' and GFAL2 'cf84f0a'

fix checksum mismatch

---

src/policy/CMSRucioPolicy/permission.py

Prevent rules without ask approval to overflow into RSEs tha require approval

---

DMOps/dynamic_ddmquota_update.py

Updates to ddm_quota script

---

docker/CMSRucioClient/loadtest/loadtest.py

Fix #515 
Lost files are automatically detached from their parent dataset. A failure in this detachment shall be investigated. 
For the second issue, this PR introduces locks on load test files at the source site. This will increase the availability guarantees for the file at the source RSE.

Add locks to loadtest files at source

---

src/policy/CMSRucioPolicy/algorithms/auto_approve.py

Fix #582 
This PR aims to limit the allowed size of the "User AutoApprove" activity to a configurable value. 
The usage limits under the activity can now be controlled using the 4 "options" defined under the "rules" section of the rucio configuration. 
- `global_usage_all_accounts`: Usage limit for the activity across all rses
- `global_usage_per_account`: Usage limit for a single account across all rses
- `single_rse_rule_size_threshold`: Usage limit for a single account when specifying a single rse as the destination
- `rule_lifetime_threshold`: Max lifetime of rules that can be auto-approved

Adding global threshold over all accounts for auto approval

---

build-rucio-images.sh
docker/rucio-server/Dockerfile
docker/rucio-ui/Dockerfile

Changes that these images include:
- Loadtest source rse rule fix: https://github.com/dmwm/CMSRucio/pull/583
- Auto approve global limit fix: https://github.com/dmwm/CMSRucio/pull/590

Removing EGI and WLCG yum configurations

---

src/policy/CMSRucioPolicy/permission.py

Fixes #597 
The changes introduced by this PR prevent rule creation to Tier3 or Tier0 sites under "Auto Approval" activity.

Prevent auto approval on T3 and T0 rses

---

docker/CMSRucioClient/loadtest/loadtest.py

Fixes #602 
This PR adds `ask_approval` to new loadtest rules for Tape RSEs that require approval.

Add ask approval for tape rules in loadtest

---

docker/rucio-upgrade/Dockerfile

Made source file paths relative to CWD (the top of the project).

update for rucio 32.0.0 .

---

src/policy/CMSRucioPolicy/algorithms/auto_approve.py

This PR makes the policy algorithm compatible with the new auto_approve function requirements, introduced in the following PR
https://github.com/rucio/rucio/pull/6215

Refactoring auto_approve function

---

src/policy/CMSRucioPolicy/permission.py

This PR updates permissions to allow users to update their own rules.
Users can update the following fields:
- 'lifetime', 
- 'state',
-  'comment',
-  'purge_replicas', 
- 'cancel_requests', 
- 'source_replica_expression', 
- 'child_rule_id'
Case 1: If this rule is not asked for approval (manual or auto) as captured by the `ignore_account_limit` field of the rule. Indicating that the user created the rule under their quota. 
- all fields mentioned above can be updated without restrictions
Case 2: If the rule was asked for approval under `User AutoApprove` activity
- Lifetime can be extended in steps of `single_extension_limit`
- Lifetime (Since the rule creation) cannot go beyond `extended_lifetime_limit` 
- All other options do not have any restrictions
FYI @drkovalskyi Let me know if …

Allow rule update permissions to users

---

src/policy/CMSRucioPolicy/permission.py

Allow all users to list usage for all others

---

docker/CMSRucioClient/scripts/CMSRSE.py
docker/CMSRucioClient/scripts/setRucioFromGitlab

Fix #636 
This PR allows site-admins and site support to control the `loadtest=True` or `loadtest=False` attribute from storage.json within the sites site_conf.

Update loadtest from siteconf

---

docker/rucio-consistency/build_image.sh

update cc to 4.5.0

---

docker/rucio-probes/Dockerfile

Add Maggie's probe changes

---

src/policy/CMSRucioPolicy/permission.py

The restricted attribute list will prevent users (including admins and operators) from modifying unwanted attributes.
For e.g. We want to prevent archive monitoring step performed by FTS on MIT_Tape; this requires that `archive_timeout` is not set on the RSE.
Fixes https://github.com/dmwm/CMSRucio/issues/726

The restricted attribute list will prevent

---

src/policy/CMSRucioPolicy/schema.py

Update schema to use 99 characters for data-tier length.
set name same as lfn length; 500
More details: https://github.com/dmwm/CMSRucio/issues/744#issuecomment-2004403959

Update datatier regex to match with WMCore and DBS expressions

---

docker/rucio_client/scripts/CMSRSE.py

Rebase of https://github.com/dmwm/CMSRucio/pull/725

match rule regex with prefix

---

helpers/README.md
helpers/fetch_locality.py

Adding script / commands for a common rest api request performed by operators

Add fetching locality instructions to helper scripts

---

src/policy/CMSRucioPolicy/permission.py

Fix https://github.com/dmwm/CMSRucio/issues/759

prevent rule creation without lifetime for tape rses

---

.github/workflows/rucio-release-images.yml

Fix https://github.com/dmwm/CMSRucio/issues/775

Update checkout version to 4

---

helpers/README.md
helpers/test_http_tape_rest_api.py

- Update the default dataset to use a MINIAOD block
- Correct typo for `rule_id`
- Correct read rule URL parsing
- Correct typo in readme for `readtorse` flag

Make minor corrections to helper script

---

docker/rucio_client/scripts/user_to_site_mapping.py
docker/rucio_client/scripts/utils.py

Use rfc2553dn generator in user_to_site_mapping.py

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Add a PR template to the repo

---

helm/rucio-consistency/Chart.yaml
helm/rucio-consistency/templates/jobber-configmap.yaml
helm/rucio-consistency/values.yaml

Modify CC helm charts: Add possibility to specify resultSinks

---

docker/rucio-daemons/Dockerfile

Will upgrade integration to 34.4.1 and this patch should already be included there

Remove patch 6444

---

docker/rucio_client/Dockerfile

Update voms rpms

---

src/policy/CMSRucioPolicy/permission.py

- even when using ask_approval as the rule will be auto approved

Analysis TapeRecal should be allowed to have multiple RSEs 

---

docker/rucio-daemons/Dockerfile

> Remove with Rucio35 upgrade
Required by: https://its.cern.ch/jira/browse/CMSDM-192
FYI @ericvaandering

Patch overwrite on disk until rucio 35 upgrade

---

docker/rucio-daemons/Dockerfile
docker/rucio-server/Dockerfile

Fix dst file report for files that are on tape

---

docker/rucio-daemons/Dockerfile
docker/rucio-server/Dockerfile

https://github.com/dynamic-entropy/rucio/pull/2

Add patch to generate cms dataset scoped tokens to CMS Rucio images

---

docker/rucio-daemons/Dockerfile
docker/rucio-probes/Dockerfile
docker/rucio-server/Dockerfile
docker/rucio-ui/Dockerfile
docker/rucio_client/Dockerfile
src/policy/CMSRucioPolicy/__init__.py
src/policy/CMSRucioPolicy/algorithms/pfn2lfn.py

We have been successfully running Rucio 35 for over a week now, and it has performed well. I propose we merge these changes into the master branch and continue further development from there.

Merge Rucio 35

---

src/policy/CMSRucioPolicy/permission.py

Use config_get_int instead of config_get to get an integer config value

---

docker/rucio-daemons/Dockerfile
docker/rucio-server/Dockerfile

Revert "Patch rucio PR 7199"

---

src/policy/CMSRucioPolicy/permission.py

Signature changed, needs string scope, not internal scope

Fix auto approval

---

src/policy/CMSRucioPolicy/__init__.py
src/policy/CMSRucioPolicy/algorithms/tape_collocation.py

Corrects problem seen in integration while running the tape metadata policy
cc @ericvaandering

Corrected problem in policy package code

---

src/policy/CMSRucioPolicy/algorithms/tape_collocation.py

* Changes the way the policy is registered, so it can be properly called 
* Adds logging statements

Correct order of registation for the tape collocation policy

---

src/policy/CMSRucioPolicy/algorithms/tape_collocation.py

Correct initialization

---

src/policy/CMSRucioPolicy/permission.py

When add rule fails due to permission being denied, an error message detailing the exception is displayed using the PermissionResult described in [rucio/rucio#65680](https://github.com/rucio/rucio/issues/6580).
Relevant issues: #867 #545 
Fixes #545

Fix 867 Added error messages when add rule fails 

---

docker/rucio-probes/Dockerfile

Probes: Update RSE settings and attributes, disable requests volume and count

Probes: Update and disable

---

docker/rucio-probes/Dockerfile

Revert "Apply probes volume patch"

---

docker/wf-dashboard/.ipynb_checkpoints/build_image-checkpoint.sh
docker/wf-dashboard/Dockerfile
docker/wf-dashboard/build_image.sh
docker/wf-dashboard/rucio.cfg
helm/rucio-cron-jobs/Chart.yaml
helm/rucio-cron-jobs/templates/cronjobs.yaml
helm/rucio-cron-jobs/values.yaml

Helm chart and docker image added for new WF dashboard

wf-dashboard added
